### ISSUE TITLE
Not supported with latest 3.0.0-preview5

### ISSUE THREAD

**Issue by furqansafdar** [jsakamoto/Toolbelt.Blazor.LoadingBar#1]
Hope the library will be compliant with latest 3.0.0-preview5 soon.

**Comment by jsakamoto** [comment]
Oh, I'm sorry for missing push my latest commits into this repository.

However, [the NuGet Package of this library ver.5](https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/) should be worked well!

Sample project files: [BZLApp.zip](https://github.com/jsakamoto/Toolbelt.Blazor.LoadingBar/files/3202123/BZLApp.zip)

**Comment by enkodellc** [comment]
How about the now latest 3.0.0-preview6?

**Comment by jsakamoto** [comment]
Thank you for heads up of me.

I'm checking it, and migrating it if necessary, at tonight.

**Comment by jsakamoto** [comment]
"Blazor (client-side) LoadingBar (Toolbelt.Blazor.LoadingBar)" ver.6.0.0 was released!

- https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/6.0.0
