### ISSUE TITLE
On version 3.2.0 js and css files are not found

### ISSUE THREAD

**Issue by sdagkas** [jsakamoto/Toolbelt.Blazor.LoadingBar#14]
Using version 3.2.0 of wasm the files "/_content/Toolbelt.Blazor.LoadingBar/script.min.js" and "/_content/Toolbelt.Blazor.LoadingBar/style.min.css" return a 404 not found.

**Comment by jsakamoto** [comment]
The sample site that is using v.3.2.0 of wasm works fine.

- https://github.com/jsakamoto/Toolbelt.Blazor.LoadingBar/blob/master/SampleSite/Client/SampleSite.Client.csproj#L9

Please tell me more detail about your problem.

Could you attach all of your project files to this thread?

**Comment by jsakamoto** [comment]
@sdagkas 

Is this topic helpful for you?

- https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/issues/21#issuecomment-596161453

**Comment by sdagkas** [comment]
> @sdagkas
> 
> Is this topic helpful for you?
> 
> * [jsakamoto/Toolbelt.Blazor.I18nText#21 (comment)](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/issues/21#issuecomment-596161453)

@jsakamoto  That did the trick! Thanks a lot!
