### ISSUE TITLE
How to inject enableIntercept in AddHttpClient()

### ISSUE THREAD

**Issue by liongkj** [jsakamoto/Toolbelt.Blazor.LoadingBar#16]
Sorry, i am not sure whether this is a correct place to ask.
I tried to inject the loading bar to typed client, but I have no idea how to achieve this because i read the docs that "AddHttpClient" auto make DI as transient.

this is my code:
```csharp
builder.Services.AddHttpClient<FirebaseFunctionClient>(client =>
                        client.BaseAddress = new Uri(builder.Configuration["FirebaseSetting:CloudFunctionsUrl"])
                    )
                .EnableIntercept(this); //<-----
```

**Comment by jsakamoto** [comment]
@liongkj Hi!

I updated the sample site to use "Typed client".

https://github.com/jsakamoto/Toolbelt.Blazor.LoadingBar/blob/master/SampleSite/Client/Program.cs#L27

```csharp
builder.Services.AddHttpClient<WeatherForecastService>((sp, client) =>
{
    client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);

    // If you want to use Typed Client, please invoke "EnableIntercept()" here.
    client.EnableIntercept(sp);
});
```

A notable point is, the `AddHttpClient<T>` extension method has some overload versions.
One of them has an argument that is a callback function that receives two arguments - those arguments are `IServiceProvider` and `HttpClient`.

I hope this sample code will resolve your issue.

**Comment by liongkj** [comment]
Thanks, I Can't Thank You Enough!
