### ISSUE TITLE
Make color of the loading bar configurable via options

### ISSUE THREAD

**Issue by hypervtechnics** [jsakamoto/Toolbelt.Blazor.LoadingBar#17]

**Comment by jsakamoto** [comment]
@hypervtechnics Sorry too late!
Thank you proposal, so I published the new version of the Blazor Loading Bar just now!

- https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/12.1.0

It can be configurable the color of the loading bar via options.

```csharp
builder.Services.AddLoadingBar(options =>
{
  // Specify the color of the loading bar
  // by CSS color descriptor.
  options.LoadingBarColor = "yellow";
});
```

For more detail, please se also the ["README"](https://github.com/jsakamoto/Toolbelt.Blazor.LoadingBar#configure-the-color-of-the-loading-bar) document.

**Comment by hypervtechnics** [comment]
Wow great! Thank you very much :)
