### ISSUE TITLE
Not supported with .NET Core 3 Preview 9

### ISSUE THREAD

**Issue by Berrysoft** [jsakamoto/Toolbelt.Blazor.LoadingBar#4]
The signature of `IJSRuntime.InvokeAsync` has changed, thus making the mono linker failed.

**Comment by jsakamoto** [comment]
Did you try to use Toolbelt.Blazor.LoadingBar **ver.7** ?

- https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/7.0.0

It should be work fine due to comiit a3fa1be07bf318868c5e6d06fedf9637f0258ff1.

**Comment by Berrysoft** [comment]
It compiles, thanks!
