### ISSUE TITLE
Ops. In 3.1.0-preview3.19553.2 don't work 

### ISSUE THREAD

**Issue by parad74** [jsakamoto/Toolbelt.Blazor.LoadingBar#5]
In 3.1.0-preview3.19553.2 don't work 
In Blazor Client-Side 
In 3.1.0-preview2 was very well

**Comment by jsakamoto** [comment]
Thank you for your report!

I fixed this issue, and I published the NuGet packages of new version just now.

- [Toolbelt.Blazor.LoadingBar - v.8.0.0](https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/8.0.0)
- and it's dependency, [Toolbelt.Blazor.HttpClientInterceptor - v.6.0.0](https://www.nuget.org/packages/Toolbelt.Blazor.HttpClientInterceptor/6.0.0)
