### ISSUE TITLE
LoadingBar not working with Blazor 3.1 Preview 4

### ISSUE THREAD

**Issue by pablopioli** [jsakamoto/Toolbelt.Blazor.LoadingBar#6]
In the last preview of Blazor they make a breaking change. Static assets are not loaded automatically anymore.

https://github.com/aspnet/AspNetCore/issues/17596

So, the loading bar does not appears as the Javascript code wasn't loaded.
You should include them manually with something like that
_content/Toolbelt.Blazor.LoadingBar/script.js
but this doesn't work. I guess the library should be recompiled (Net Standard 2.1 is required now)

For now, as a workaround you can include the js and css files in the wwwroot folder of your project.

**Comment by jsakamoto** [comment]
Thank you for your report!

Sorry too late, but I fixed this issue, and I published ver.9!

- https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/

ver.9 will work fine on Blazor 3.1. Preview 4.

Please try it out!

**Comment by pablopioli** [comment]
Yes, working fine in the last Blazor preview!

Thanks for your work.
