### ISSUE TITLE
LoadingBar not working with Blazor 3.2

### ISSUE THREAD

**Issue by pablopioli** [jsakamoto/Toolbelt.Blazor.LoadingBar#9]
As usual a new Blazor version breaks the dependencies

**Comment by pablopioli** [comment]
I tinkered a bit with your code
https://github.com/pablopioli/Toolbelt.Blazor.LoadingBar

The interest part is where to add the UseXXX method, now it just depends on if you need a host or not.

I made something like that

            var builder = WebAssemblyHostBuilder.CreateDefault(args);

            builder.Services.AddLoadingBar();

            builder.RootComponents.Add<App>("app");

            var host = builder.Build();

            host.UseLoadingBar();

            await host.RunAsync();

**Comment by jsakamoto** [comment]
I published latest version that supports Blazor WebAssembly v.3.2 preview1. 😄 

- https://www.nuget.org/packages/Toolbelt.Blazor.LoadingBar/

Thank you for your suggestion!
